apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-workload-identity # needs to be unique per namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    clientID: "dbc8b27c-028d-419d-961f-4d81e8ad8cd4" # Setting this to use workload identity
    keyvaultName: cloud-h2t-kv     # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: andrei-lipinski-2
          objectType: secret
          objectVersion: ""
    tenantId: f5ac0f9b-7407-4d23-8587-2940daec5669        # The tenant ID of the key vault